services:
  - type: web
    name: railguard-backend
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: IP_CAM_URL
        value: http://10.200.57.8:8080/video
      - key: CONFIDENCE_THRESHOLD
        value: "0.5"
      - key: ALERT_COOLDOWN_SECONDS
        value: "5"
      - key: MONGODB_URI
        value: mongodb+srv://nitheeshscse2024_db_user:fiOND00t49MkW9yv@cluster0.zjpfezy.mongodb.net
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
